### ISSUE TITLE
question(Code Connect in React): child components doesn't appear in Component playground view

### ISSUE THREAD

**Issue by lauthieb** [figma/sds#3]
Hello, 

Thanks a lot for this amazing example of a Design System!!!

I'm working to add Code Connect for our Button component in React which has icon inside _(start & end)_, I get inspiration from https://github.com/figma/sds/blob/main/src/figma/icons/Icons.figma.tsx (thanks a lot), in order to make it work:

```typescript
startIcon: figma.boolean("Start Icon", {
  true: figma.instance("↪ Start picker"),
  false: undefined,
}),
endIcon: figma.boolean("End Icon", {
  true: figma.instance("↪ End picker"),
  false: undefined,
}),
```

Unfortunately, this works only in the Dev Mode sidebar, the Code Connect snippet in component playground is not the same.

Sidebar: ✅

![CleanShot 2024-06-27 at 15 59 44](https://github.com/figma/sds/assets/9600228/ef4995de-7e2f-4730-91c1-445c1f8cbd4e)

Component playground: ❌

![CleanShot 2024-06-27 at 16 00 23](https://github.com/figma/sds/assets/9600228/fcfcd8a6-5ca5-4395-b31f-1e9052a0baf8)

Do you have the same problem on your side, please?

Thank you in advance for your help!

**Comment by jake-figma** [comment]
This is great feedback and a bug in Figma. I have forwarded to the team. Thanks so much!
